### ISSUE TITLE
Fix virtual key haptic feedback

### ISSUE THREAD

**Issue by martincz** [Grarak/android_device_oneplus_oneplus2#11]
https://github.com/MoKee/android_device_oneplus_tocino/commit/0fb274ebd95153e9a2324c700535328970dbe6ae

**Comment by Grarak** [comment]
I don't really want to overwrite the Generic file.
And a further problem is that home key will keep vibrating even after unchecking "wake device"

**Comment by martincz** [comment]
I think we don't have choose, unless we can make finger print work...

**Comment by Grarak** [comment]
I will try to get fingerprint running. If I can't get it working I will modify framework base so home button does not vibrate all the time.

**Comment by Grarak** [comment]
Ok merged your commit.
