### ISSUE TITLE
Audio Bass Crackling & Distorted in Earphones op2 major issue cm 13

### ISSUE THREAD

**Issue by shaktishekhar** [Grarak/android_device_oneplus_oneplus2#32]
https://download.cyanogenmod.org/get/jenkins/164937/cm-13.0-20160608-NIGHTLY-oneplus2.zip

Radio/baseband: MPSSS.BO.2.c9-00015-M8994FAAAANAZM-1

Kernel version: 3.10.84

Model: oneplus2

Component/s: Audio

Affects Version/s: 13.0

When i turn the volume up the bass of any audio or sound crackles or gets distorted in earphones or speaker . default music app youtube are fine 

apps which use own lib files like spotify,saavan,power amp not working well at all 

PFA 

i attached the sample audio coming from headphone (Tried hard to record the headphone output in recording) playable in android this issue is present from the 1st official build of CM 13 Nightly

not only me there are friends of mine who own the exact phone "oneplus two" having the same issue without xposed,viper,supersu or any3rd party alteration in the rom. please consider this 

issue , i tested the same with official latest oxygen os 3.0.2 everything is perfect there on full volume bass and everything.

Thank You 

Regards' 

Shakti Shekhar

@shaktishekhar "xda" id

http://goo.gl/Ywj1h0 
Logcat, and sample audio in the link above

**Comment by friendyy** [comment]
Yes , me and my friends also tested this

**Comment by DerkSoul** [comment]
I PREFER CM OS OVER ALL OTHER OS AND I FIND SERIOUS ISSUES the audio is cracking up. I am a music lover and everyday i face the same problems regarding songs. Please do solve all these as fast as possible. And do listen to the sample audio and logcat. As fast as possible. 
http://goo.gl/Ywj1h0

**Comment by sahilr05** [comment]
Yea .... Even i'm facing the same issue

**Comment by vijaywidluv** [comment]
Yes am also facing this problem. Its good in mid or low but when I try to volume up, it starts crackling. I hope it get fixed soon as its ruining my audio listening experience.. Overall am loving this official cm.

**Comment by pechalive** [comment]
Same here! The sound is horrible... It's the single issue that I face it on CM13 20160608.

**Comment by ihor-sviziev** [comment]
Also this issue reported in official CM github issues: https://github.com/CyanogenMod/android_device_oneplus_oneplus2/issues/15

**Comment by thdervenis** [comment]
Same issue here. Bass is horrible, music is unlistenable. Only issue with CM13 on OP2

**Comment by iammido** [comment]
Issue fixed with this commit. 
mido:
https://review.cyanogenmod.org/#/c/148594/
@shaktishekhar confirmed issue resolution after applying the patch. Issue is good to close.

**Comment by shaktishekhar** [comment]
[https://docs.google.com/uc?authuser=0&id=0B_qkJGXx6zg-OVJCaENWNEdvVTA&export=download](url) patch fix untill official fix

**Comment by ihor-sviziev** [comment]
:open_mouth: These changes were merged to official CM repo. Next nightly build will contains it!
:tada:
