### ISSUE TITLE
Dual sim mode - Sim cards not initialized on build 20160613

### ISSUE THREAD

**Issue by ihor-sviziev** [Grarak/android_device_oneplus_oneplus2#34]
After upgraded from nightly 20160611 to 20160613 - my sim cards is not unlocked, when I go to settings >> sim cards - all fields are disabled. Unlock sim is not apearing after reboot.

No custom kernel or other stuff was installed.

./adb logcat all: 
[logcat.txt](https://github.com/Grarak/android_device_oneplus_oneplus2/files/311655/logcat.txt)

On XDA forums this issue also conformed: http://forum.xda-developers.com/oneplus-2/orig-development/rom-official-cyanogenmod-13-t3392278/post67296640#post67296640

**Comment by Grarak** [comment]
Are you encrypted?

**Comment by ihor-sviziev** [comment]
@Grarak no

**Comment by Grarak** [comment]
Try a clean install

**Comment by shaktishekhar** [comment]
@Grarak Please look for the animation issue :(

**Comment by ihor-sviziev** [comment]
@Grarak I did factory resed & re-installed 0613 build, but have same issue. Logcat attached:
[logcat_clean.txt](https://github.com/Grarak/android_device_oneplus_oneplus2/files/311701/logcat_clean.txt)

**Comment by Grarak** [comment]
Does baseband in settings->info appears?

**Comment by ihor-sviziev** [comment]
@Grarak  Yes,  Baseband version: MPSS.BO.2.5.c9-00015-M8994FAAAANAZM-1, IMEI code also shows correctly, but sim 1 status and sim 2 status shows as "SIM not inserted".

**Comment by Grarak** [comment]
Are you using 2 sim cards?

**Comment by ihor-sviziev** [comment]
@Grarak yes. Both of them are inserted right now

**Comment by Grarak** [comment]
Try to use only one

**Comment by DerkSoul** [comment]
@Grarak where the hell have you been to. I have been forwarding my issue regarding the animation thing. And as a developer you are not even replying a single time. I used to respect your work. But after this kinda activity its really annoying. What issues are you solving as a developer . its been an official already and yet these bugs are not yet solved. What the hell is wrong with it. I have really got irritated with all these things. Please work upon it. First solve this issue then make latest builds. SOLVE THE BUGS FASTER.

**Comment by ihor-sviziev** [comment]
@Grarak I have no ability to check it right now, but I can check it 5 hours later.
Seems like this issue doesn't happens for A2005 and A2003 devices (according to XDA thread), I have A2001. Maybe it related specially for this model?
Do you have any other questions? I could check all of them together

**Comment by Grarak** [comment]
I have A2001 as well. But I only use one sim right now

**Comment by ihor-sviziev** [comment]
@Grarak Do you have any questions more? maybe I could give you some additional logs?

**Comment by voron00** [comment]
Hey, on latest build (13.06) i can only use LTE network. When i try switch to 2G i get emergency calls only. It was a clean install with nano opengapps and A2001 model. LTE works fine though. On previous build all was good.

**Comment by ihor-sviziev** [comment]
@Grarak I checked, if I have one sim card in first or second slot - it works good, but when I insert second sim card - both sim cards don't work at all.

**Comment by Grarak** [comment]
solved
