### ISSUE TITLE
Flash Light Switch Gesture is causing Phone Restart

### ISSUE THREAD

**Issue by souvikdas95** [Grarak/android_device_oneplus_oneplus2#36]
Sometimes, in one gesture, or in several gestures denoting shape "V" or "U" causes the Phone to restart instead of simply tuning on and off the Flash/Torch. Flash is not broken as tested with the Camera App. In any case, Flash doesn't work with gestures anymore.
Build: 13 June, 2016

**Comment by Grarak** [comment]
Can you stop creating issues? It's already fixed

**Comment by souvikdas95** [comment]
I apologise. I am new to Github.
