### ISSUE TITLE
Custom dtbtool for oneplus 2, unnecessary modify device/qcom/common

### ISSUE THREAD

**Issue by martincz** [Grarak/android_device_oneplus_oneplus2#6]
http://review.mfunz.com/#/c/12340/

**Comment by martincz** [comment]
and this one

**Comment by martincz** [comment]
http://review.mfunz.com/#/c/12339/

**Comment by Grarak** [comment]
Yeah thanks. I was thinking about to move it to device tree. But unfortunately the modified still doesn't build a working dt.img.

**Comment by martincz** [comment]
Ok... I thought it already worked. I haven't test because I'm very busy in today.

**Comment by Grarak** [comment]
should be fixed

**Comment by martincz** [comment]
Yes, you did it. : )
